---
deploymentservers:
  hosts:
    deployment1:
<<<<<<< HEAD
      ansible_host: 52.232.67.91
      ansible_port: 22
      ansible_ssh_user: jenkins
  vars:
    ansible_python_interpreter: /usr/bin/python3
=======
      ansible_host: 34.79.12.33
      ansible_port: 22
      ansible_ssh_user: rg
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    deployment1:
      ansible_host: 34.79.12.33
      ansible_port: 22
      ansible_ssh_user: rg
  vars:
    ansible_python_interpreter: /usr/bin/python3
>>>>>>> 2d8568be4d8de0b733fad4283460f06dd988d9a9
